image: node:6.9.3

services:
  - mysql:5.7.16
  - redis:3.0.7

variables:
  MYSQL_DATABASE: shard
  MYSQL_ROOT_PASSWORD: FhfLaS4uzv5qwnPh

cache:
  paths:
    - node_modules/

stages:
  - test

before_script:
  - npm install -q

execute npm tests:
  stage: test
  script:
    - cp server/config/gitlab_ci.js server/config/local.js
    - npm run lint
    - npm run cover
